include:
  - board: eyelash_sofle_right
    shield: eyelash_sofle_right nice_view
  - board: eyelash_sofle_left
    shield: eyelash_sofle_left nice_view
  - board: nice_nano_v2
    shield: settings_reset
